version: 2.1

parameters:
  release_kedro:
    type: boolean
    default: false
  run-nightly:
    type: boolean
    default: false
  run-hourly:
    type: boolean
    defualt: false

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.1

workflows:
  regular:
    jobs:
      # the path-filtering/filter job determines which pipeline
      # parameters to update, i.e. which builds to run.
      - path-filtering/filter:
          name: check-updated-files
          base-revision: main
          config-path: .circleci/continue_config.yml
          # <regex path-to-test> <parameter-to-set> <value-of-pipeline-parameter>
          mapping: |
            docs/.* docs_change true
            ^((?!docs/).)*$ code_change true
